# Optimized Python Implementation(s)

In the previous workbooks, a simple implementation was provided in pure python. For a number of reasons, extension modules are provided by Numpy, SciPy, etc. for optimized matrix operations. The redblackgraph module also provides extension model implementations that are described below

## rb.array / rb.matrix

The redblackgraph module provides two Numpy-like implementations, one of array (rbarray) and one of matrix (rbmatrix).

The distinctive characteristics of these classes are matrix multiplication has been overridden to support Red Black Graph linear algebra.

For example:

In [1]:
from redblackgraph import array, matrix, warshall
import numpy as np

In [2]:
A = array([[-1,  2,  3,  0,  0],
             [ 0, -1,  0,  2,  0],
             [ 0,  0,  1,  0,  0],
             [ 0,  0,  0, -1,  0],
             [ 2,  0,  0,  0,  1]], dtype=np.int64)

In [3]:
A_star = A @ A @ A
A_star

array([[-1,  2,  3,  4,  0],
       [ 0, -1,  0,  2,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0, -1,  0],
       [ 2,  4,  5,  8,  1]])

In [4]:
u = array([[2, 0, 0, 0, 0]])
v = array([[0],
             [3],
             [0],
             [0],
             [0]])
u_lambda = u @ A_star
v_lambda = A_star @ v

In [5]:
u_lambda

array([[2, 4, 5, 8, 0]])

In [6]:
v_lambda

array([[5],
       [3],
       [0],
       [0],
       [9]])

**note:** Rank 1 arrays can cause unexpected results. See: [Notes from Andrew Ng Lecture](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/87MUx/a-note-on-python-numpy-vectors)

In [8]:
warshall(array([[-1,  2,  3,  0,  0],
             [ 0, -1,  0,  2,  0],
             [ 0,  0,  1,  0,  0],
             [ 0,  0,  0, -1,  0],
             [ 2,  0,  0,  0,  1]], dtype=np.int64))

(array([[-1,  2,  3,  4,  0],
        [ 0, -1,  0,  2,  0],
        [ 0,  0,  1,  0,  0],
        [ 0,  0,  0, -1,  0],
        [ 2,  4,  5,  8,  1]]), array(3, dtype=int32))