# Optimized Python Implementation

In the previous workbooks, a simple implementation was provided in pure python. For performance optimized linear algebra operations, extension modules are provided by Numpy, SciPy, etc. The redblackgraph module also provides extension model implementations that are described below

## rb.array / rb.matrix

The redblackgraph module provides two Numpy-like implementations, one of array and one of matrix.

The distinctive characteristics of these classes are matrix multiplication has been overridden to support Red Black Graph linear algebra. As well as methods being defined for `transitive_closure` and `relational_composition`

For example:

In [1]:
import redblackgraph as rb
import numpy as np

In [2]:
A = rb.array([[-1,  2,  3,  0,  0],
              [ 0, -1,  0,  2,  0],
              [ 0,  0,  1,  0,  0],
              [ 0,  0,  0, -1,  0],
              [ 2,  0,  0,  0,  1]], dtype=np.int64)

In [3]:
A_star = A @ A @ A
A_star

array([[-1,  2,  3,  4,  0],
       [ 0, -1,  0,  2,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0, -1,  0],
       [ 2,  4,  5,  8,  1]])

In [4]:
u = rb.array([[2, 0, 0, 0, 0]])
v = rb.array([[0],
              [3],
              [0],
              [0],
              [0]])
u_lambda = u @ A_star
v_lambda = A_star @ v

In [5]:
u_lambda

array([[2, 4, 5, 8, 0]])

In [6]:
v_lambda

array([[5],
       [3],
       [0],
       [0],
       [9]])

In [13]:
%%timeit
A = rb.array([[-1,  2,  3,  0,  0],
              [ 0, -1,  0,  2,  0],
              [ 0,  0,  1,  0,  0],
              [ 0,  0,  0, -1,  0],
              [ 2,  0,  0,  0,  1]], dtype=np.int64)
A_star, diameter = A.transitive_closure()


10.4 µs ± 277 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
print(f"A_star:\n{A_star} \ndiameter: {diameter}")

A_star:
[[-1  2  3  4  0]
 [ 0 -1  0  2  0]
 [ 0  0  1  0  0]
 [ 0  0  0 -1  0]
 [ 2  4  5  8  1]] 
diameter: 3


In [11]:
%%timeit
u = rb.array([[2, 0, 0, 0, 0, 1]])
v = rb.array([[0],
              [0],
              [0],
              [0],
              [0],
              [1]])
A_lambda = A_star.relational_composition(u, v)

50.2 µs ± 2.98 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [12]:
print(f"A_lambda:\n{A_lambda}")

A_lambda:
[[-1  2  3  4  0  0]
 [ 0 -1  0  2  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0 -1  0  0]
 [ 2  4  5  8  1  0]
 [ 2  4  5  8  0  1]]
